services:
  green-api:
    image: ${DOCKER_IMAGE}
    ports:
      - "3002:3000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - multi-container-service_default

networks:
  multi-container-service_default:
    external: true
